### ISSUE TITLE
Avoid mount animation on iron sight exit

### ISSUE THREAD

**Issue by Duion** [Duion/Uebergame#155]
If you exit iron sight, the weapon is mounted again and the animation that is also played when mounting a gun for the first time is played with its sound, maybe should be disabled somehow, it can be annoying

**Comment by ZOD2015** [comment]
The only way with the current system is to change the weapons stateSequence from "switch_in" to  "idle". However this results in the weapon just appearing in the hand when first cycled to.

**Comment by Duion** [comment]
Yes, I thought about doing that, but both versions are a bit ugly and I already removed the switch sound, so it becomes less annoying.

**Comment by Duion** [comment]
I also integrated a resource that lets you set image state through script, it is used for the new reload function, this could be used for iron sight/ mounting weapons as well, so for example you set to play a mount animation on choosing a weapon through the number keys, but in the state machine there will be no mounting animation so it will not play on iron sight exit.

**Comment by Duion** [comment]
I used the cheap solution to disable the mount animation, this should solve it for now. The issue can be reopened if there should be new player and weapon models.
