### ISSUE TITLE
Feature Request: Basic building instructions in README

### ISSUE THREAD

**Issue by g4jc** [Duion/Uebergame#159]
Hello,
I am attempting to build this project from source (rather than using the binary build), in order to create a proper PKGBUILD for Arch User Repository. However, I haven't been able to do so successfully.

Following the instructions here, I believe I already have the required dependencies for the game engine:
http://wiki.torque3d.org/coder:compiling-in-linux

1) Download  https://github.com/Duion/Torque3D (Engine)
2) Compile ??? (seems to be missing a cmake build folder?)
3) Download https://github.com/Duion/Uebergame
4) Combine these folders by some way, and then make a binary / package file.

Sorry if this is an obvious question, but I'm unfamiliar with compiling for the Torque Engine. So far no one else has done so either, at least on AUR.

Thanks!

**Comment by Duion** [comment]
Cmake will ask you where the source code is, just point it to the Torque3D main directory and chose a folder where to place the makefiles (usually under My Projects/Uebergame-64-bit or something) and the resulting binaries will be placed in the games root directory, that should be all.

Maybe I will write a tutorial some time, but I did not think it is that complicated, the tutorial I linked covers most of the process.
Originally Torque3D used a project manager program that created a template for you and generated the files for compiling, but this one has been discontinued. It worked by placing your project under Torque3D/My Projects/Uebergame/ and then you had a buildfiles/ folder and a game/ folder, the game folder contained the game files and the compiled binary would be placed into it.
You can do it the same way, but in reality all you need to do is point cmake at Torque3D and compile and place the binary into the root folder of the game repository, so don't let that confuse you.
