### ISSUE TITLE
Crash on startup with Intel HD graphics and AMD Radeon on GNU/Linux

### ISSUE THREAD

**Issue by Hiradur** [Duion/Uebergame#212]
On two of my systems Uebergame 1.0.6.0 crashes on startup with the same error message:

```
Initializing platform...
Input Init:
% 
DebugDrawer Enabled!
GFX Init:
   Null device found
% 
--------- Loading DIRS ---------
Loading Directory: 
Loading Directory: levels
Loading Directory: art;levels
Loading Directory: scripts;art;levels
% 
--------- Parsing Arguments ---------
% 
--------- Starting Uebergame ---------
----- Adding missions to list -----
PB_Gummifeld_arena_b added to mission list
PB_Gummifeld_field_d added to mission list
PB_Gummifeld_field_b added to mission list
PB_Gummifeld_arena_a added to mission list
PB_Gummifeld_field_a added to mission list
PB_Gummifeld_field_c added to mission list
PB_Gummifeld added to mission list
TG_DesertRuins_dawn added to mission list
TG_DesertRuins_night added to mission list
TG_DesertRuins_storm added to mission list
TG_DesertRuins_day added to mission list
TG_DirtPit_day added to mission list
TG_DirtPit_night added to mission list
TG_DirtPit_dawn added to mission list
TG_DirtPit_rain added to mission list
TG_BuildingSite_day added to mission list
TG_BuildingSite_dawn added to mission list
TG_BuildingSite_rain added to mission list
TG_BuildingSite_night added to mission list
TG_Fields_day added to mission list
TG_Fields_night added to mission list
TG_Fields_dawn added to mission list
TG_Fields_rain added to mission list
Binding server port to default IP
UDP initialized on port 0
The requested renderer, D3D9, doesn't seem to be available. Trying the default, OpenGL.
The OpenGL renderer doesn't seem to be available. Trying the GFXNulDevice.
Attempting to create GFX device: GFX Null Device []
Initializing GFXCardProfiler (GFX Null Device Renderer)
   o Chipset : 'NULL Device'
   o Card    : 'GFX Null Device Card'
   o Version : '0'
   o VRAM    : 0 MB
   - Scanning card capabilities...
   - Loading card profiles...
      - Loaded card profile scripts/client/profile/GFXNullDeviceRenderer.cs
<input> (0): Unable to find function GFXCardProfiler::setCapability
      - No card profile scripts/client/profile/GFXNullDeviceRenderer.NULLDevice.cs exists
      - No card profile scripts/client/profile/GFXNullDeviceRenderer.NULLDevice.GFXNullDeviceCard.cs exists
      - No card profile scripts/client/profile/GFXNullDeviceRenderer.NULLDevice.GFXNullDeviceCard.0.cs exists
Device created, setting adapter and enumerating modes
% Segmentation fault (core dumped)
```

Systems:
1: Debian testing, Linux 4.8, Intel HD graphics 520, FOSS driver
2: Ubuntu Studio 16.04, Linux 4.4, AMD Radeon HD 7770, FOSS driver

This may be a duplicate of #96 but for some reason I'm unable to open this issue (error 500).

**Comment by Duion** [comment]
It does not detect the video drivers and switches to null device.
The open video drivers are currently not supported, the game only works with the proprietary drivers.

**Comment by Hiradur** [comment]
>The open video drivers are currently not supported, the game only works with the proprietary drivers.

Is this a limitation of the Torque 3D engine or what is the issue?
There is no proprietary driver for Intel GPUs and the proprietary driver for AMD is difficult to install on modern Ubuntu.

**Comment by Duion** [comment]
No, there is no limitation, just issues, but it can work.
Lets wait until the next version comes out, should be this month, then we will see, if it runs then.

**Comment by colbyrussell** [comment]
I had the same issues after downloading 1.0.6.0 last week.  I"m using Ubuntu 16.04 with Intel HD Graphics 5500.

I checked with 1.0.7.0 earlier today, and found no problems (other than poor performance on this machine).

**Comment by Duion** [comment]
Yes, support for that seems to have been added in 1.0.7.0.

**Comment by Hiradur** [comment]
1.0.7.0 works fine, thank you.

**Comment by im-grey** [comment]
I still have this name problem with the latest version, but even without the graphics card in my system it still segfaults.

**Comment by im-grey** [comment]
My version of the game is 1.0.9.0-1 specifically. Without the card it just segfaults and crashes. With the card it just freezes at the point where it would normally crash.

**Comment by Duion** [comment]
Probably a driver issue, mesa drivers should work now, but for proper performance I would recommend the proprietary drivers.
What version are you using and what graphics drivers?

**Comment by im-grey** [comment]
1.0.9.0-1 and the open source drivers.

**Comment by Duion** [comment]
What distribution, what GPU and what drivers exactly are you using?

**Comment by im-grey** [comment]
Xbuntu and AMD Radeon HD6450 ATI-102-C26405(B), the drivers being the latest ones from the Xbuntu repos.

**Comment by Duion** [comment]
Well I cannot do much in that case, using the open source drivers is often problematic here and there. Using the proprietary drivers will probably fix most issues, otherwise you have to wait for things to get better.
