### ISSUE TITLE
frameAllocator.h(108,0): {Fatal} - Error alloc too large, increase frame size!

### ISSUE THREAD

**Issue by ckorn** [Duion/Uebergame#222]
Hi,

just trying to compile Ubergame for the Ubuntu gaming site playdeb.net

When starting the game I see the splash screen but then there is this error:
```
% - Initializing Sketch Tool
Executing tools/convexEditor/convexEditor.cs.
Executing tools/convexEditor/convexEditorGui.gui.
Executing tools/convexEditor/convexEditorToolbar.ed.gui.
Executing tools/convexEditor/convexEditorGui.cs.
Engine initialized...
Started up in 5.98 seconds...
AntiAliasing has been disabled; it is not compatible with AdvancedLighting.
/home/korn/packages/ubergame/engine/Torque3D/Engine/source/core/frameAllocator.h(108,0): {Fatal} - Error alloc too large, increase frame size!
Platform::debugBreak: triggering SIGSEGV for core dump
% Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
```

**Comment by Duion** [comment]
Did you build a debug build of the binary? You need to make a release build, the debug build will give errors.

**Comment by Duion** [comment]
Can I close this?

**Comment by ckorn** [comment]
Unlike the compilation guide says there is a special release flag which has to be enabled:
```
cmake ../../../.. -DTORQUE_APP_NAME=Uebergame -DCMAKE_BUILD_TYPE=Release -DTORQUE_BUILD_TYPE=Release
```

**Comment by Duion** [comment]
The error just exists in my version and otherwise you should enable release build, otherwise you get bad performance and debug information in the console.

**Comment by Duion** [comment]
I think I will just set it to "Release" by default in my engine fork.
