### ISSUE TITLE
Update new assets for steam

### ISSUE THREAD

**Issue by rogersachan** [Duion/Uebergame#230]
https://steamcommunity.com/groups/steamworks/announcements/detail/1597002662762032240

Now requires boxart (600x900), logo, and background for the game page.

**Comment by Duion** [comment]
I knew about that in advance, but I was lazy. A lot of "professional" game developers also seem to be lazy and have not added the new box art yet, so it does not seem that bad. If you want you can make new boxart and I will add it, if it is decent.

**Comment by rogersachan** [comment]
@Duion what assets did you use for the existing steam tile? if you can link me to them or other art assets and the logo I can get on it right away.

**Comment by Duion** [comment]
I zipped up my Steam images development folder, maybe this is of use for you, I thought you could extract it from the page, but the development files may be more helpful:
https://duion.com/files/temp/uebergame_steam_images.zip
It is all kind of improvised, I wanted to improve the logos later, but I never got to it, so if you think you can do it better, let your creativity flow.

**Comment by rogersachan** [comment]
![uebergame-logo](https://user-images.githubusercontent.com/7173984/68547726-d290fa00-03b2-11ea-8d4d-7491ca9a260e.png)
![bockart](https://user-images.githubusercontent.com/7173984/68547727-d290fa00-03b2-11ea-869c-7da854ef75e3.png)
![eox](https://user-images.githubusercontent.com/7173984/68547728-d290fa00-03b2-11ea-83a4-613ae8595ee5.jpg)
[newsteamassets.zip](https://github.com/Duion/Uebergame/files/3828725/newsteamassets.zip)
Please use the zip for the uncompressed versions when uploading. These images are large per steam's requirement and github probably will compress them heavily.

**Comment by rogersachan** [comment]
https://partner.steamgames.com/doc/store/libraryassets goes over the new assets now that boxart is in stable.

**Comment by Duion** [comment]
They are all wrong size and/or format and some are missing, I probably have to look into it and make them myself.

**Comment by Duion** [comment]
I did them myself, hope you are happy now.
