### ISSUE TITLE
Console key is not bindable to another key

### ISSUE THREAD

**Issue by Duion** [Duion/Uebergame#32]
On my keyboard the "ö" key opens the console and this cannot be changed somehow, I could bind a new key to open the console but the old one still stays. I want the console removed from the "ö" since that is needed in german.

**Comment by RichardsGameStudio** [comment]
It is also defined in \core\scripts\client\core.cs. Mayby do a file-search at toggleConsole, because that function is responsable for the console.

**Comment by Duion** [comment]
Thanks, I think that removed it.
https://github.com/Duion/Uebergame/commit/a92c78ec2a68f17b7b2784717a50b60175fa70bc
