### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by Mailaender** [Duion/Uebergame#45]
At the moment I can only guess which commit is version 0.02, but I need a tarball for Linux packaging.

**Comment by Mailaender** [comment]
See https://github.com/Duion/Uebergame/releases

**Comment by Duion** [comment]
Master branch is always the latest release.

**Comment by titiger** [comment]
I strongly suggest tags too

**Comment by Duion** [comment]
I created a release of the current master branch, hope that is the way it should be.
