### ISSUE TITLE
Lag when trying to move cursor around

### ISSUE THREAD

**Issue by owlg** [Duion/Uebergame#53]
I don't really know what the performance issue is, but will be willing to provide any, given instructions. When I try to move the cursor, it lags, making aiming very difficult.

**Comment by Calinou** [comment]
Is V-Sync enabled in the game or forced in your graphics driver? In any case, it will increase input lag.

**Comment by Duion** [comment]
Maybe you have your graphics settings too high, so your computer cannot handle it, try with lower settings.

**Comment by owlg** [comment]
@Duion I lowered all the graphics settings to low, the problem still persists.

**Comment by Duion** [comment]
See if you have mouse acceleration enabled in your operating system and disable it, if it is enabled.

**Comment by Duion** [comment]
Does this problem still persists even with lower graphics and mouse acceleration disabled? In most cases it is either a performance problem or mouse settings problem.
