### ISSUE TITLE
Weapon keys (especially mine) should be configurable

### ISSUE THREAD

**Issue by Calinou** [Duion/Uebergame#55]
The <kbd>KP4</kbd> key does not work on GNU/Linux (at least on AZERTY keyboard layouts), so you can't select mines at all.

Making it configurable would partially fix this problem.

**Comment by Duion** [comment]
There will be a completely new weapon selecting system, which I'm currently working at.

**Comment by Duion** [comment]
Weapon slots now use keys 1-8, which can also be configured in options menu, so issue closed.
