### ISSUE TITLE
Can't switch to a weapon if out of ammo, even if ammo packs were collected for it

### ISSUE THREAD

**Issue by Calinou** [Duion/Uebergame#56]
For example, you can't switch to primary weapon if out of ammo, even if you collected ammo packs after switching to pistol. The weapon will reload if you didn't switch to another weapon yet, but it won't if you did switch to another weapon like the pistol.

A possible fix is to let the player switch to weapons with no ammo (there needs to be an "out of ammo" warning of some sort, like an audible click when trying to fire).

**Comment by Duion** [comment]
This should be fixed now with the new weapon reloading system.
