### ISSUE TITLE
Game settings are not saved in linux

### ISSUE THREAD

**Issue by titiger** [Duion/Uebergame#58]
Whatever I do I get no saved game settings.
What I try:
1. choose screenresolution
2. choose fullscreen
3. apply ( game changes resolution and Fullscreenmode )
4. exit game ( I see no errors on Console )
1. restart games and all settings are lost

**Comment by Calinou** [comment]
If you close the game using <kbd>Alt+F4</kbd>, are the settings saved?

**Comment by Duion** [comment]
Is this issue still there?
The settings are not saved if you exist the game through a crash or if you kill the app, but if you exit regularly it should be saved.
Only thing I can imagine is that the operating system blocks write permission or something.

**Comment by dimibyte** [comment]
#160 Possible fix

**Comment by Duion** [comment]
Yes, probably fixed by now, the options settings save on closing the menu or closing the game. So if you set somethign without properly exiting it is not saved, but there is an additional save now, so it should work now.
