### ISSUE TITLE
Intel Graphics - Linux - Ubergame 1.0.4.0 Seg Fault on Start-up

### ISSUE THREAD

**Issue by MajorLunaC** [Duion/Uebergame#96]
Linux Mint 17.3 'Rosa', 64-bit + 32-bit compatibility. Intel integrated graphics Intel Core i5-4670 CPU, HD Graphics 4600.

When I start up the game, I get this:

> `
> $ ./Uebergame 
> Initializing platform...
> Input Init:
> % 
> Failed to load OpenAL shared library. Sound will not be available
> SFXALProvider - OpenAL not available.
> DebugDrawer Enabled!
> GFX Init:
>    Null device found
> % 
> --------- Loading DIRS ---------
> % 
> --------- Parsing Arguments ---------
> Binding server port to default IP
> UDP initialized on port 0
> The requested renderer, D3D9, doesn't seem to be available. Trying the default, OpenGL.
> The OpenGL renderer doesn't seem to be available. Trying the GFXNulDevice.
> Attempting to create GFX device: GFX Null Device []
> Initializing GFXCardProfiler (GFX Null Device Renderer)
>    o Chipset : 'NULL Device'
>    o Card    : 'GFX Null Device Card'
>    o Version : '0'
>    o VRAM    : 0 MB
> - Scanning card capabilities...
> - Loading card profiles...
>   - No card profile core/profile/GFXNullDeviceRenderer.cs exists
>   - No card profile core/profile/GFXNullDeviceRenderer.NULLDevice.cs exists
>   - No card profile core/profile/GFXNullDeviceRenderer.NULLDevice.GFXNullDeviceCard.cs exists
>   - No card profile core/profile/GFXNullDeviceRenderer.NULLDevice.GFXNullDeviceCard.0.cs exists
>     Device created, setting adapter and enumerating modes
>     % Segmentation fault
>     `

Note that another FOSS Torque3D game works fine on my system, although it's only 32-bit for some reason:
https://github.com/fr1tz/terminal-overload
http://www.terminal-overload.org/

**Comment by Duion** [comment]
The graphics card/driver does not get detected.
You can try to download an older version of the game, like 1.0.3.5, it has only 32-bit Linux in case you think it is related to that.

**Comment by MajorLunaC** [comment]
Version 1.0.3.5 gives the exact same output, so it's not about the 32-bit part. If it helps, you could take a look at how that other project searches for resources. Mint, and maybe other xubuntu derivatives, seem to place things in odd places, I think.

**Comment by Elinvention** [comment]
I have the same issue on Debian testing on AMD Radeon HD 6670, Mesa 11.1.2.

**Comment by Duion** [comment]
Yes, Mesa drivers do not work.

**Comment by MajorLunaC** [comment]
I do hope you will support Mesa drivers in the future. They're extremely capable, and update with significant features and extensions often. They also support more advanced versions of OpenGL, but also support Direct3D. Please consider supporting Mesa drivers.

**Comment by Duion** [comment]
I'm not a graphics programmer.

**Comment by Calinou** [comment]
As far as I know, it's an upstream Torque 3D issue, see [this issue](https://github.com/GarageGames/Torque3D/issues/1233).

**Comment by Hiradur** [comment]
This may be fixed in 1.0.7.0, see #212

**Comment by Duion** [comment]
This should be fixed by now.
